export const types = {

    //for create employee
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    CREATE_EMPLOYEE_SUCCESS: "CREATE_EMPLOYEE_SUCCESS",
    CREATE_EMPLOYEE_ERROR: "CREATE_EMPLOYEE_ERROR",

    //for update employee
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
    UPDATE_EMPLOYEE_ERROR: "UPDATE_EMPLOYEE_ERROR",

    //for delete employee
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
    DELETE_EMPLOYEE_ERROR: "DELETE_EMPLOYEE_ERROR",

    //to get employees list
    GET_EMPLOYEES: "GET_EMPLOYEES",
    GET_EMPLOYEES_SUCCESS: "GET_EMPLOYEES_SUCCESS",
    GET_EMPLOYEES_ERROR: "GET_EMPLOYEES_ERROR",

    //to get employee
    GET_EMPLOYEE: "GET_EMPLOYEE",
    GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
    GET_EMPLOYEE_ERROR: "GET_EMPLOYEE_ERROR",

    //to clear create and update states
    CLEAR_EMPLOYEE_SUCCESS: "CLEAR_EMPLOYEE_SUCCESS",

    //to clear delete success
    CLEAR_DELETE_SUCCESS: "CLEAR_DELETE_SUCCESS"
}